### ISSUE TITLE
Allow to redefine the size of the root disk for Clouds that support it

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStream#228]
opennebula: slipstream/SlipStreamConnectors#140
ec2: SixSq/SlipStreamConnectors#73

**Comment by mebster** [comment]
From Slack (slipstream channel):

lionel [2:33 PM] 
In preparation of DFMS we implemented the extra disk feature into the EC2 connector.
But now they are asking to be able to configure the size of the root disk instead of an extra disk.
@meb @cal: What should I reply ?

meb [2:45 PM] 
Interesting idea. Create an issue and we'll discuss it. We need to understand how this will map to all other connectors and clouds, or not.

lionel [2:55 PM] 
I think @khaled did it for OpenNebula by using the common `disk` parameter that was introduced for PRS.

meb [3:02 PM] 
Cool.  How would it work for OpenStack, Exoscale and OTC?  Do we have a new optional `disk` parameter?  Is it in the cloud section?  What happens when the cloud doesn’t support it?  Or do we feel we have a good enough coverage?

**Comment by schaubl** [comment]
> How would it work for OpenStack, Exoscale and OTC?

`Exoscale`: Per instance type there is a list of available disk size like 10G, 50G, 100G, ... . It is already implemented in the Exoscale connector as a Cloud specific parameter.
`OpenStack` and `OTC`: The root disk size is part of the Flavour (Instance Type) so you select it by selecting the Flavour. If the size is 0 in the selected Flavour, the root disk will have the size of the Cloud Image. However it seems to be possible to "start from a volume" in which case we should be able to select the size of the root disk but I never tried it.

> Do we have a new optional disk parameter? Is it in the cloud section?

This parameter has been added in the Cloud section along with CPU and RAM to allow to search a service offer with PRS.

> What happens when the cloud doesn’t support it?
 
The root disk size come either from the size of the Cloud image or from the Instance Type.

> Or do we feel we have a good enough coverage?

Currently except (maybe) OpenNebula, no connector support it AFAIK

**Comment by 0xbase12** [comment]
OpenNebula support root disk redefinition. I used as Lionel said the common disk parameter:
https://github.com/slipstream/SlipStreamClient/commit/6d80d9caaaa5080880efd7d82799ef1fce113b32
https://github.com/slipstream/SlipStreamConnectors/commit/7dcf3faddb8da6915e05fa36499a6bd24e8ba5a7

**Comment by mebster** [comment]
Is this on top of or instead of the `extra disk` feature?

**Comment by schaubl** [comment]
On top of

**Comment by schaubl** [comment]
Basically what is left is OpenStack and OTC
