### ISSUE TITLE
Convert module to CIMI resource

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStream#292]
- [x] Create two basic CIMI resources for module: `module` and `version`
- [x] Create a migration script

**Comment by loomis** [comment]
See PRs for further details and historical comments.

A full conversion of the modules on Nuvla to a CIMI representation has been performed on a test SlipStream deployment.  The full conversion took a bit under 3 hours (167 minutes) with the script running on a laptop separate from Nuvla and the test machine.

The known limitations of the migration script are:

 - ACLs are not migrated:
      * Decision on how to map the build, run, other rights in the ACLs.
      * Decision on what to do with ACL inheritance.
 - Treatment of connector-specific options.
 - Creation/updated dates are currently reset to current date. Determine how to preserve these.

As there are now "project" resources, the module resource implementation needs to check/ensure consistency in the module hierarchy: not allow addition of modules without a parent, check ACL of enclosing project, no duplication of paths, etc.

The errors that arise in the conversions are summarized below:

 - References to non-existent components.
 - Components without a parent component/image reference.
 - Module changed type image/component in its history.
 - Invalid parameter/node names.
 - Other invalid parameters: ram, author, os. 
 - Character encoding issues.

The character encoding problems need to be fixed in the migration script. The others problems require us to decide what to do with invalid module specifications: try to correct errors, ignore modules, etc.

**Comment by mebster** [comment]
How are we solving the cloud specific image id issue?  Partial update?  Something else?  The issue shows-up when we add NuvlaBoxes, where the current model requires updating each module targeting the new box.

**Comment by loomis** [comment]
Continued with slipstream/SlipStreamServer#1611.
