### ISSUE TITLE
Allow SlipStream administrators to choose the kind of contextualization to use for Linux and Windows machines

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStream#69]
This can be implemented as two dropdown menu with the following content. 
Kind of contextualization for Linux:
- Cloud (cloud-init, ...)
- SSH

Kind of contextualization for Windows:
- Cloud (CloudBase-init, ...)
- WinRM

Alternatively it can be implemented with two checkboxes:
- [ ] SSH contextualization for Linux
- [ ] WinRM contextualization for Windows

Or even one dropdown menu with the following content:
Use Cloud contextualization:
- No (use SSH and WinRM instead)
- For Linux (use WinRM for Windows)
- For Windows (use SSH for Linux)
- For both

**Comment by schaubl** [comment]
@slipstream/owners @slipstream/crew : Which version do you prefer (see above) ?

**Comment by rbf** [comment]
To make it similar to other options in the configuration, I'd go for the unified dropdown, although a bit simplified:

    Use native cloud contextualisation:
       - Never
       - Only for Linux
       - Only for Windows
       - Always

I'd write the rest of the explanation (i.e. saying that SSH and WinRM will be used instead of contextualisation) in the corresponding help-hint.

*Question:* Is this options expected to be available for both user profile and run dialogs? (We've realised that it's often useful to do so...).

**Comment by schaubl** [comment]
> Question: Is this options expected to be available for both user profile and run dialogs? (We've realised that it's often useful to do so...).

Currently this option will be only in the system parameters of the Cloud.
But later on, it may be added to Cloud image parameters.
